version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd django_front && yarn start"
    ports:
      - "3000:3000"